AllCops:
  Exclude:
    - 'bin/*'
    - '**/Rakefile'
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
